const officers = [
  {
    name: "Lu Bu",
    life: " SS 191",
    musou: " SS 96",
    attack: " S  182",
    defense: " SS 96",
    growth: " B  67",
    osr: " 888 ",
  },
  {
    name: "Tadakatsu Honda",
    life: " A  182",
    musou: " A  91",
    attack: " S  124",
    defense: " SS 124",
    growth: " S  64",
    osr: " 777 ",
  },
  {
    name: "Hu San Niang",
    life: " A",
    musou: " A",
    attack: " B",
    defense: " B",
    growth: " S  76",
    osr: " 666 ",
  },
  {
    name: "Keiji Maeda",
    life: " A",
    musou: " A",
    attack: " S  168",
    defense: " SS",
    growth: " S",
    osr: " 777 ",
  },
  {
    name: "Ying Bu",
    life: " S  179",
    musou: " S",
    attack: " A  90",
    defense: " A",
    growth: " B",
    osr: " 666 ",
  },
  {
    name: "Yu Ji",
    life: " C",
    musou: " C  54",
    attack: " C  70",
    defense: " B",
    growth: " A",
    osr: " 444 ",
  },
  {
    name: "Zhong Li Mei",
    life: " A  179",
    musou: " A",
    attack: " A",
    defense: " A  90",
    growth: " B",
    osr: " 666 ",
  },
  {
    name: "Zhang Liang",
    life: " S",
    musou: " S  83",
    attack: " D",
    defense: " A  98",
    growth: " S",
    osr: " 666 ",
  },
  {
    name: "Zuo Ci",
    life: " SS 168",
    musou: " SS",
    attack: " S  84",
    defense: " S  84",
    growth: " B  59",
    osr: " 888 ",
  },
  {
    name: "Cao Cao",
    life: " S  81",
    musou: " S  51",
    attack: " B  41",
    defense: " S  41",
    growth: " A  29",
    osr: " 777 ",
  },
  {
    name: "Hideyoshi Toyotomi",
    life: " S",
    musou: " S  51",
    attack: " B",
    defense: " A  65",
    growth: " S",
    osr: " 777 ",
  },
  {
    name: "Hua Rong",
    life: " S",
    musou: " S",
    attack: " A",
    defense: " A  104",
    growth: " A",
    osr: " 777 ",
  },
  {
    name: "Huang Gai",
    life: " A  162",
    musou: " A",
    attack: " B  81",
    defense: " A  81",
    growth: " A  57",
    osr: " 666 ",
  },
  {
    name: "Jiang Taigong",
    life: " S",
    musou: " S",
    attack: " C  58",
    defense: " A",
    growth: " A  41",
    osr: " 666 ",
  },
  {
    name: "Kanetsugu Naoe",
    life: " SS 193",
    musou: " SS 107",
    attack: " B  97",
    defense: " A  97",
    growth: " S  68",
    osr: " 777 ",
  },
  {
    name: "Liu Bei",
    life: " B  193",
    musou: " B",
    attack: " B  97",
    defense: " A  97",
    growth: " S  68",
    osr: " 555 ",
  },
  {
    name: "Mao Dun",
    life: " A",
    musou: " A",
    attack: " A",
    defense: " A  114",
    growth: " S  80",
    osr: " 666 ",
  },
  {
    name: "Master Lao",
    life: " A  170",
    musou: " A",
    attack: " B  85",
    defense: " B",
    growth: " S",
    osr: " 666 ",
  },
  {
    name: "Pang De ",
    life: " A",
    musou: " A",
    attack: " B",
    defense: " S  104",
    growth: " A",
    osr: " 666 ",
  },
  {
    name: "Pang Tong",
    life: " C",
    musou: " C  78",
    attack: " C",
    defense: " B  93",
    growth: " S",
    osr: " 444 ",
  },
  {
    name: "Ranmaru Mori",
    life: " A  170",
    musou: " A",
    attack: " B",
    defense: " A  85",
    growth: " B",
    osr: " 555 ",
  },
  {
    name: "Sun Quan",
    life: " A  170",
    musou: " A",
    attack: " C  85",
    defense: " A",
    growth: " A",
    osr: " 555 ",
  },
  {
    name: "Taishi Ci",
    life: " A",
    musou: " A",
    attack: " S  85",
    defense: " S  85",
    growth: " A",
    osr: " 777 ",
  },
  {
    name: "Tiger",
    life: " A",
    musou: " A",
    attack: " A  104",
    defense: " D",
    growth: " A",
    osr: " 555 ",
  },
  {
    name: "Wei Yan",
    life: " B  193",
    musou: " B  107",
    attack: " B  97",
    defense: " A  97",
    growth: " S  68",
    osr: " 555 ",
  },
  {
    name: "Wu song",
    life: " S  242",
    musou: " S  107",
    attack: " S",
    defense: " A",
    growth: " B",
    osr: " 777 ",
  },
  {
    name: "Xiahou Yuan",
    life: " A",
    musou: " A",
    attack: " A",
    defense: " A  104",
    growth: " A",
    osr: " 666 ",
  },
  {
    name: "Yuan Shao",
    life: " S  107",
    musou: " S",
    attack: " C  54",
    defense: " A  54",
    growth: " B  38",
    osr: " 666 ",
  },
  {
    name: "Zhang Jiao",
    life: " C  107",
    musou: " C",
    attack: " C  54",
    defense: " A  54",
    growth: " S  38",
    osr: " 444 ",
  },
  {
    name: "Zhang Liao",
    life: " S",
    musou: " S",
    attack: " A  104",
    defense: " A",
    growth: " B",
    osr: " 666 ",
  },
  {
    name: "Zhou Yu",
    life: " B  170",
    musou: " B",
    attack: " B  85",
    defense: " A",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Zhuge Liang",
    life: " C  136",
    musou: " C  78",
    attack: " C  68",
    defense: " B  68",
    growth: " S  48",
    osr: " 444 ",
  },
  {
    name: "Cao Pi",
    life: " S  101",
    musou: " S",
    attack: " C  51",
    defense: " A  51",
    growth: " A  35",
    osr: " 666 ",
  },
  {
    name: "Cao Ren",
    life: " A",
    musou: " A",
    attack: " B",
    defense: " S  98",
    growth: " A",
    osr: " 666 ",
  },
  {
    name: "Dong Zhuo",
    life: " S",
    musou: " S",
    attack: " S  152",
    defense: " A",
    growth: " B",
    osr: " 777 ",
  },
  {
    name: "Gongsun Sheng",
    life: " B  179",
    musou: " B  75",
    attack: " C",
    defense: " A",
    growth: " B",
    osr: " 444 ",
  },
  {
    name: "Guan Yu",
    life: " A",
    musou: " A  101",
    attack: " S  116",
    defense: " A",
    growth: " S",
    osr: " 777 ",
  },
  {
    name: "Han Xin",
    life: " B  75",
    musou: " B  48",
    attack: " C  38",
    defense: " B  38",
    growth: " A  27",
    osr: " 444 ",
  },
  {
    name: "Huang Zhong",
    life: " A",
    musou: " A",
    attack: " A  55",
    defense: " A  55",
    growth: " S",
    osr: " 666 ",
  },
  {
    name: "Ina",
    life: " B  130",
    musou: " B  75",
    attack: " B  65",
    defense: " B  65",
    growth: " A  46",
    osr: " 555 ",
  },
  {
    name: "Jiang Wei",
    life: " C",
    musou: " C  101",
    attack: " B",
    defense: " A  116",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Lu Meng",
    life: " C  182",
    musou: " C  101",
    attack: " B  91",
    defense: " A  91",
    growth: " SS 64",
    osr: " 555 ",
  },
  {
    name: "Lu Xun",
    life: " B",
    musou: " B",
    attack: " C  83",
    defense: " A  83",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Lu Zhishen",
    life: " S  110",
    musou: " S",
    attack: " S",
    defense: " A",
    growth: " A  39",
    osr: " 777 ",
  },
  {
    name: "Masamune Date",
    life: " B",
    musou: " B  101",
    attack: " B  116",
    defense: " A",
    growth: " B",
    osr: " 555 ",
  },
  {
    name: "Meng Huo",
    life: " S",
    musou: " S",
    attack: " S  152",
    defense: " S",
    growth: " B",
    osr: " 777 ",
  },
  {
    name: "Musashi Miyamoto",
    life: " A  217",
    musou: " A",
    attack: " B  109",
    defense: " A",
    growth: " S",
    osr: " 666 ",
  },
  {
    name: "Nagamasa Azai",
    life: " S",
    musou: " S  101",
    attack: " B",
    defense: " A  116",
    growth: " B",
    osr: " 666 ",
  },
  {
    name: "Sakon Shima",
    life: " B",
    musou: " B",
    attack: " A  55",
    defense: " A  55",
    growth: " S",
    osr: " 666 ",
  },
  {
    name: "Sun Shang Xiang",
    life: " B",
    musou: " B  75",
    attack: " B",
    defense: " A  90",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Sima Yi",
    life: " C  101",
    musou: " C",
    attack: " C  51",
    defense: " A  51",
    growth: " S  36",
    osr: " 444 ",
  },
  {
    name: "Sun Jian",
    life: " A",
    musou: " A",
    attack: " A  83",
    defense: " S  83",
    growth: " A",
    osr: " 666 ",
  },
  {
    name: "Zhang Fei",
    life: " A",
    musou: " A  101",
    attack: " S  116",
    defense: " A",
    growth: " S",
    osr: " 777 ",
  },
  {
    name: "Zhang He",
    life: " S",
    musou: " S",
    attack: " B  98",
    defense: " B",
    growth: " B",
    osr: " 666 ",
  },
  {
    name: "Zhao Yun",
    life: " B  182",
    musou: " B  101",
    attack: " A  91",
    defense: " A  91",
    growth: " S  64",
    osr: " 666 ",
  },
  {
    name: "Zhou Tai",
    life: " B  165",
    musou: " B",
    attack: " A  83",
    defense: " A",
    growth: " A",
    osr: " 555 ",
  },
  {
    name: "Zhu Rong",
    life: " B  156",
    musou: " B",
    attack: " A  78",
    defense: " A  78",
    growth: " S  55",
    osr: " 666 ",
  },
  {
    name: "Genghis Khan",
    life: " S",
    musou: " S",
    attack: " S",
    defense: " A  52",
    growth: " S  37",
    osr: " 777 ",
  },
  {
    name: "Ginchiyo Tachibana",
    life: " A",
    musou: " A",
    attack: " B  94",
    defense: " A",
    growth: " B",
    osr: " 555 ",
  },
  {
    name: "Gu Dasao",
    life: " S",
    musou: " S",
    attack: " B",
    defense: " A  103",
    growth: " B  72",
    osr: " 666 ",
  },
  {
    name: "Guan Ping",
    life: " B  219",
    musou: " B  96",
    attack: " B",
    defense: " B",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Hanzo Hatori",
    life: " A  188",
    musou: " A",
    attack: " B",
    defense: " A",
    growth: " A",
    osr: " 666 ",
  },
  {
    name: "Hua Tuo",
    life: " A  119",
    musou: " A  45",
    attack: " C",
    defense: " B",
    growth: " A",
    osr: " 555 ",
  },
  {
    name: "Huyuan Zhuo",
    life: " S",
    musou: " S",
    attack: " S  78",
    defense: " A  78",
    growth: " A",
    osr: " 777 ",
  },
  {
    name: "Ieyasu Tokugawa",
    life: " S  170",
    musou: " S  71",
    attack: " B",
    defense: " A",
    growth: " B",
    osr: " 666 ",
  },
  {
    name: "Kenshin Uesugi",
    life: " S",
    musou: " S",
    attack: " S  94",
    defense: " A",
    growth: " A",
    osr: " 777 ",
  },
  {
    name: "Lin Chong",
    life: " S",
    musou: " S",
    attack: " A  78",
    defense: " A",
    growth: " S  55",
    osr: " 777 ",
  },
  {
    name: "Liu Bang",
    life: " B  124",
    musou: " B  71",
    attack: " B  62",
    defense: " A  62",
    growth: " S  44",
    osr: " 555 ",
  },
  {
    name: "Mitsuhide Akechi",
    life: " S  124",
    musou: " S  71",
    attack: " B  62",
    defense: " A  62",
    growth: " A  44",
    osr: " 666 ",
  },
  {
    name: "Mitsunari Ishida",
    life: " A  73",
    musou: " A  45",
    attack: " B  37",
    defense: " A  37",
    growth: " S  26",
    osr: " 666 ",
  },
  {
    name: "Nene",
    life: " A",
    musou: " A  71",
    attack: " B",
    defense: " B  85",
    growth: " A",
    osr: " 555 ",
  },
  {
    name: "Nobunaga Oda",
    life: " S",
    musou: " S  45",
    attack: " B  60",
    defense: " A",
    growth: " S",
    osr: " 777 ",
  },
  {
    name: "Noh",
    life: " B  170",
    musou: " B  71",
    attack: " D",
    defense: " B",
    growth: " A",
    osr: " 444 ",
  },
  {
    name: "Qiong Ying",
    life: " A",
    musou: " A  96",
    attack: " A  110",
    defense: " B",
    growth: " S",
    osr: " 666 ",
  },
  {
    name: "Sun Er Niang",
    life: " B",
    musou: " B",
    attack: " B  78",
    defense: " B",
    growth: " B  55",
    osr: " 444 ",
  },
  {
    name: "Sun Ce",
    life: " A",
    musou: " A",
    attack: " A  78",
    defense: " A  78",
    growth: " S",
    osr: " 666 ",
  },
  {
    name: "Xiahou Dun",
    life: " S  96",
    musou: " S",
    attack: " A  48",
    defense: " A  48",
    growth: " B  34",
    osr: " 666 ",
  },
  {
    name: "Xiao He",
    life: " A",
    musou: " A",
    attack: " D",
    defense: " B",
    growth: " B  60",
    osr: " 444 ",
  },
  {
    name: "Xing Cai",
    life: " B",
    musou: " B  96",
    attack: " C",
    defense: " A  110",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Xu Huang",
    life: " A 96",
    musou: " A",
    attack: " A 48",
    defense: " A 48",
    growth: " A 34",
    osr: " 666 ",
  },
  {
    name: "Xu Zhu",
    life: " S 188",
    musou: " S",
    attack: " S",
    defense: " A",
    growth: " A",
    osr: " 777 ",
  },
  {
    name: "Yoshihiro Shimazu",
    life: " A",
    musou: " A",
    attack: " S",
    defense: " A",
    growth: " A  66",
    osr: " 666 ",
  },
  {
    name: "Yue Ying",
    life: " B  173",
    musou: " B  96",
    attack: " B  87",
    defense: " B  87",
    growth: " S  61",
    osr: " 555 ",
  },
  {
    name: "Yukimura Sanada",
    life: " A  173",
    musou: " A  96",
    attack: " A  87",
    defense: " A  87",
    growth: " A  61",
    osr: " 666 ",
  },
  {
    name: "Zhen Ji",
    life: " B",
    musou: " B",
    attack: " B  52",
    defense: " A  52",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Zhu Wu",
    life: " A  188",
    musou: " A",
    attack: " D",
    defense: " A",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Da Qiao",
    life: " C 162",
    musou: " C 68",
    attack: " B",
    defense: " A",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Dian Wei",
    life: " A",
    musou: " A",
    attack: " S",
    defense: " A 88",
    growth: " B",
    osr: " 666 ",
  },
  {
    name: "Diao Chan",
    life: " B  119",
    musou: " B  68",
    attack: " C  60",
    defense: " B  60",
    growth: " S  42",
    osr: " 555 ",
  },
  {
    name: "Gan Ning",
    life: " B",
    musou: " B",
    attack: " S  113",
    defense: " A",
    growth: " A",
    osr: " 666 ",
  },
  {
    name: "Guan Sheng",
    life: " S",
    musou: " S  91",
    attack: " S  104",
    defense: " A",
    growth: " A",
    osr: " 777 ",
  },
  {
    name: "Kotaro Fuma",
    life: " B",
    musou: " B",
    attack: " B",
    defense: " A  88",
    growth: " A",
    osr: " 555 ",
  },
  {
    name: "Ling Tong",
    life: " A  147",
    musou: " A",
    attack: " B  74",
    defense: " B",
    growth: " A",
    osr: " 555 ",
  },
  {
    name: "Ma Chao",
    life: " B",
    musou: " B  91",
    attack: " S  104",
    defense: " A",
    growth: " S",
    osr: " 666 ",
  },
  {
    name: "Magoichi Saika",
    life: " A",
    musou: " A",
    attack: " A  88",
    defense: " A",
    growth: " B",
    osr: " 666 ",
  },
  {
    name: "Oichi",
    life: " A",
    musou: " A  91",
    attack: " C",
    defense: " B  104",
    growth: " S",
    osr: " 555 ",
  },
  {
    name: "Okuni",
    life: " B 70",
    musou: " B 44",
    attack: " D 35",
    defense: " B 35",
    growth: " S 25",
    osr: " 444 ",
  },
  {
    name: "Shingen Takeda",
    life: " S  162",
    musou: " S  68",
    attack: " C",
    defense: " B",
    growth: " A",
    osr: " 666 ",
  },
  {
    name: "Xiang Yu",
    life: " S",
    musou: " S",
    attack: " S  97",
    defense: " SS 97",
    growth: " A",
    osr: " 888 ",
  },
  {
    name: "Xiao Qiao",
    life: " C",
    musou: " C  68",
    attack: " B",
    defense: " B  81",
    growth: " S",
    osr: " 444 ",
  },
];
