export const departmentsList = [
  { label: "Department", value: "Any" },
  { label: "Anaesthetics", value: "Anaesthetics" },
  { label: "Cardiology", value: "Cardiology" },
  { label: "ENT", value: "ENT" },
  { label: "Gastroenterology", value: "Gastroenterology" },
  { label: "Gynecology", value: "Gynecology" },
  { label: "Hematology", value: "Hematology" },
  { label: "Neonatal", value: "Neonatal" },
  { label: "Neurology", value: "Neurology" },
  { label: "Nutrition", value: "Nutrition" },
  { label: "Obstetrics", value: "Obstetrics" },
  { label: "Oncology", value: "Oncology" },
  { label: "Ophthalmology", value: "Ophthalmology" },
  { label: "Orthopedics", value: "Orthopedics" },
  { label: "Physiotherapy", value: "Physiotherapy" },
  { label: "Renal", value: "Renal" },
  { label: "Surgery", value: "Surgery" },
  { label: "Urology", value: "Urology" },
];
